version: 1.0.{build}
image: Visual Studio 2019 Preview
skip_tags: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
build_script:
  - dotnet build ./src -c Release
test_script:
  - dotnet test src/DiscordBot.xUnit.Tests/DiscordBot.xUnit.Tests.csproj