version: 1.0.{build}
skip_tags: true
image: Visual Studio 2019 Preview
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  CODECOV_TOKEN:
    secure: zBycUTEftyF/WccvyALujEFN6KJ8GW/NJSoZc6bn+5Z6SG8uBpUK8WvtZ1SL4T94
install:
- ps: >-
    nuget install chocolatey

    choco install opencover.portable
build_script:
- cmd: dotnet build src -c Release
test_script:
- ps: >-
    cd src

    OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:test -filter:"+[DiscordBot*]* -[DiscordBot*]*Tests.*" -output:".\coverage.xml" -oldstyle