version: 1.0.{build}
image: Visual Studio 2019 Preview
before_build:
- ps: >-
    cd src

    nuget restore TeaBagBot.sln -OutputDirectory packages

    nuget install opencover -OutputDirectory packages

    nuget install codecov -OutputDirectory packages
build:
  verbosity: minimal
test_script:
- ps: >-
    packages\opencover.4.7.922\tools\OpenCover.Console.exe -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:test -filter:"+[*]* -[*]*Tests.*" -output:".\coverage.xml" -oldstyle

    packages\codecov.1.12.0\tools\win7-x86\codecov.exe -f "coverage.xml"